### ISSUE TITLE
Fails to start.

### ISSUE THREAD

**Issue by stav242** [unlobito/ha-hildebrandglow#30] opened 2021-06-13 21:04 UTC
Log Details (ERROR)
 This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/hildebrandglow/glow.py:93
Integration: Hildebrand Glow (documentation)
First occurred: 22:00:21 (1 occurrences)
Last logged: 22:00:21

Error setting up entry for hildebrandglow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hildebrandglow/__init__.py", line 30, in async_setup_entry
    await hass.async_add_executor_job(glow.retrieve_cad_hardwareId)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hildebrandglow/glow.py", line 93, in retrieve_cad_hardwareId
    self.hardwareId = cad["hardwareId"]
KeyError: 'hardwareId'

**Comment by unlobito** [comment] 2021-06-14 13:04
Duplicate of #26

**Closed as completed by unlobito** 2021-06-14 13:04 UTC
Labels: duplicate
