### ISSUE TITLE
Not appearing in HA Integrations after installing

### ISSUE THREAD

**Issue by saltinesurfer** [unlobito/ha-hildebrandglow#33] opened 2021-06-16 16:18 UTC
Hi there, i've added the repository as per instructions, installed the integration via HACS, restarted, cleared browser cache, and gone to HA integrations, however Hildebrand Glow isn't in the list of available integrations to setup :( Any ideas? 

I'm running HASSIO 5.13, core-2021.6.2

Any help would be much appreciated!

Thanks,

**Comment by danstreeter** [comment] 2021-06-16 16:27
Duplicate of #29 - and solution is in there =)

**Comment by saltinesurfer** [comment] 2021-06-16 20:36
> Duplicate of #29 - and solution is in there =)

Many thanks for the pointer. Not sure why, but when I toggle show beta, it greys out, presumably fetching the versions, but then doesn't show anything different to before with 0.0.3 as the highest.. I'll try again tomorrow. 

Did I read that the latest beta requires a glow stick CAD? I don't have one yet as they are OOS, so will need to rely on the bright app api polling to start with.

**Comment by unlobito** [comment] 2021-06-17 17:50
Hey @rob-da, that's correct- this currently only works with a CAD since the integration relies on MQTT for retrieving data but #26 covers extending the integration to retrieve data over REST (necessary for DCC).

**Closed as completed by unlobito** 2021-06-17 17:50 UTC
Labels: duplicate
